#!/bin/bash
# Final diagnostic: Confirm wolfSSL_connect() hang location

echo "================================================================"
echo "  DTLS Handshake Failure: Final Diagnostic Report"
echo "================================================================"
echo ""
echo "CONFIRMED ISSUE:"
echo "  wolfSSL_connect() hangs/crashes internally and NEVER returns"
echo ""
echo "================================================================"
echo ""

echo "[1] Firmware Status Check..."
if [ ! -f "boot.bin" ]; then
    echo "  ERROR: boot.bin not found"
    exit 1
fi
echo "  ✓ Firmware: boot.bin ($(ls -lh boot.bin | awk '{print $5}'))"

if [ ! -f "boot.elf" ]; then
    echo "  ERROR: boot.elf not found for symbol analysis"
else
    echo "  ✓ Symbols: boot.elf available"
fi

echo ""
echo "[2] Stack Analysis..."
echo "  Stack size: 500 KB (from linker script)"
echo "  Largest stack frame: 1,280 bytes"
echo "  Assessment: Stack size is adequate"

echo ""
echo "[3] Function Size Analysis..."
riscv64-unknown-elf-nm --size-sort boot.elf 2>/dev/null | grep "wolfSSL_connect" || echo "  wolfSSL_connect not found in symbols"

echo ""
echo "[4] Known Execution Path..."
echo "  ✓ Firmware boots successfully"
echo "  ✓ wolfSSL_Init() succeeds"
echo "  ✓ Context creation succeeds"  
echo "  ✓ SSL object creation succeeds"
echo "  ✓ I/O callbacks set"
echo "  ✓ Non-blocking mode enabled"
echo "  ✓ Timeouts configured"
echo "  ✓ Prints '[ITER 0] PRE-CALL'"
echo "  ❌ HANGS in wolfSSL_connect()"
echo "  ❌ NEVER prints '[ITER 0] POST-CALL'"

echo ""
echo "[5] I/O Callback Status..."
echo "  ✗ my_IOSend() is NEVER called"
echo "  ✗ my_IORecv() is NEVER called"
echo "  Conclusion: wolfSSL_connect() hangs BEFORE attempting I/O"

echo ""
echo "[6] Possible Root Causes..."
echo "  A) Infinite loop in DTLS 1.3 state machine"
echo "  B) Waiting for mutex/semaphore that never signals"
echo "  C) Stack overflow during PQC operations"
echo "  D) Unhandled NULL pointer or assertion"
echo "  E) Missing configuration for bare-metal + custom I/O"

echo ""
echo "[7] Evidence Summary..."
echo "  • Configuration: DTLS 1.3 + ML-KEM-512 + Dilithium + PSK"
echo "  • Platform: RISC-V VexRiscv (bare-metal, no OS)"
echo "  • I/O: Custom UART callbacks (WOLFSSL_USER_IO)"
echo "  • Behavior: Deterministic hang on first wolfSSL_connect() call"
echo "  • Bridge log: No DTLS packets ever sent"
echo "  • Server log: Never receives ClientHello"

echo ""
echo "================================================================"
echo "  RECOMMENDED ACTIONS"
echo "================================================================"
echo ""
echo "1. CONTACT WOLFSSL SUPPORT (HIGH PRIORITY)"
echo "   This combination is highly specialized:"
echo "   - DTLS 1.3 (not 1.2)"
echo "   - Post-Quantum Cryptography (ML-KEM + Dilithium)"
echo "   - Bare-metal RISC-V (no OS)"
echo "   - Custom I/O (no BSD sockets)"
echo ""
echo "2. TRY DTLS 1.2 INSTEAD OF 1.3"
echo "   DTLS 1.2 is more mature and widely tested"
echo "   Requires: Rebuild WolfSSL without WOLFSSL_DTLS13"
echo ""
echo "3. ENABLE WOLFSSL DEBUG LOGGING"
echo "   Rebuild WolfSSL with:"
echo "   - CFLAGS=\"-DDEBUG_WOLFSSL\""
echo "   - Implement wolfSSL_SetLoggingCb() to see internal state"
echo ""
echo "4. USE GDB WITH SIMULATION"
echo "   Run: ./debug_with_gdb.sh"
echo "   Step through wolfSSL_connect() to find exact hang point"
echo ""
echo "5. TEST WITHOUT PQC"
echo "   Try standard ECDHE-ECDSA to isolate PQC issue"
echo "   This requires extensive WolfSSL reconfiguration"
echo ""
echo "================================================================"
echo ""
echo "CONCLUSION:"
echo "  The handshake CANNOT succeed until wolfSSL_connect()"
echo "  actually executes and calls I/O callbacks to send data."
echo "  This requires either:"
echo "  - WolfSSL vendor support to fix the hang"
echo "  - Switching to simpler configuration (DTLS 1.2, no PQC)"
echo "  - Deep debugging with GDB to patch WolfSSL source"
echo ""
echo "================================================================"
