#!/bin/bash

echo "============================================================"
echo " DTLS 1.3 Post-Quantum Cryptography Demonstration"
echo "============================================================"
echo ""
echo "This project demonstrates DTLS 1.3 with Post-Quantum"
echo "Cryptography (ML-KEM-512 + Dilithium) encryption."
echo ""
echo "============================================================"
echo " Available Demonstrations"
echo "============================================================"
echo ""

echo "1. Bundled Handshake Architecture (Working)"
echo "   └─ File: captures/dtls_pqc_bidirectional.pcap (2310 bytes)"
echo "   └─ Shows: Complete protocol architecture"
echo "   └─ Data: Unencrypted markers for clarity"
echo "   └─ Purpose: Understanding protocol flow"
echo ""

echo "2. Real Encrypted PQC Traffic (NEW!)"
echo "   └─ File: captures/dtls_pqc_real_encrypted.pcap (2521 bytes)"
echo "   └─ Shows: REAL encrypted DTLS 1.3 packets"
echo "   └─ Data: AES-128-GCM encrypted (appears random)"
echo "   └─ Purpose: Demonstrate actual encryption"
echo ""

echo "============================================================"
echo " Capture File Details"
echo "============================================================"
echo ""

if [ -f "captures/dtls_pqc_bidirectional.pcap" ]; then
    echo "✓ dtls_pqc_bidirectional.pcap"
    SIZE=$(stat -c%s captures/dtls_pqc_bidirectional.pcap 2>/dev/null)
    PACKETS=$(tcpdump -r captures/dtls_pqc_bidirectional.pcap 2>/dev/null | wc -l)
    echo "  Size: $SIZE bytes"
    echo "  Packets: $PACKETS"
    echo "  Type: Synthetic (architectural demo)"
    echo ""
fi

if [ -f "captures/dtls_pqc_real_encrypted.pcap" ]; then
    echo "✓ dtls_pqc_real_encrypted.pcap"
    SIZE=$(stat -c%s captures/dtls_pqc_real_encrypted.pcap 2>/dev/null)
    PACKETS=$(tcpdump -r captures/dtls_pqc_real_encrypted.pcap 2>/dev/null | wc -l)
    echo "  Size: $SIZE bytes"
    echo "  Packets: $PACKETS"
    echo "  Type: Real encrypted data"
    echo ""
fi

echo "============================================================"
echo " Post-Quantum Cryptography Features"
echo "============================================================"
echo ""
echo "ML-KEM-512 (Kyber) - Key Exchange"
echo "  • NIST FIPS 203 standard"
echo "  • Lattice-based cryptography"
echo "  • ~800 byte public keys"
echo "  • Quantum-resistant"
echo ""
echo "Dilithium Level 2 (ML-DSA) - Digital Signatures"
echo "  • NIST FIPS 204 standard"
echo "  • Lattice-based signatures"
echo "  • ~2420 byte signatures"
echo "  • Quantum-resistant"
echo ""
echo "AES-128-GCM - Symmetric Encryption"
echo "  • Already quantum-resistant (128-bit)"
echo "  • Authenticated encryption"
echo "  • TLS 1.3 recommended cipher"
echo ""

echo "============================================================"
echo " How to View Captures"
echo "============================================================"
echo ""
echo "Using Wireshark (GUI):"
echo "  wireshark captures/dtls_pqc_real_encrypted.pcap"
echo ""
echo "Using tcpdump (CLI):"
echo "  tcpdump -r captures/dtls_pqc_real_encrypted.pcap -vv"
echo ""
echo "Using tshark (detailed analysis):"
echo "  tshark -r captures/dtls_pqc_real_encrypted.pcap -V"
echo ""

echo "============================================================"
echo " Key Differences"
echo "============================================================"
echo ""
echo "Synthetic Demo (bidirectional.pcap):"
echo "  ✓ Shows protocol architecture clearly"
echo "  ✓ Human-readable markers"
echo "  ✓ Easy to understand packet flow"
echo "  ✗ Data not actually encrypted"
echo ""
echo "Real Encrypted Demo (real_encrypted.pcap):"
echo "  ✓ REAL encrypted data"
echo "  ✓ Shows what PQC traffic actually looks like"
echo "  ✓ Random-appearing ciphertext"
echo "  ✗ Cannot see encrypted content (by design!)"
echo ""

echo "============================================================"
echo " Documentation"
echo "============================================================"
echo ""
echo "README files:"
echo "  • captures/README_PQC_ENCRYPTED.md - Detailed explanation"
echo "  • README.md - Project overview"
echo ""

echo "============================================================"
echo " For Your Professor"
echo "============================================================"
echo ""
echo "Show BOTH captures:"
echo ""
echo "1. dtls_pqc_bidirectional.pcap"
echo "   → Explains the protocol design"
echo "   → Shows all steps clearly"
echo "   → Demonstrates bundled verification concept"
echo ""
echo "2. dtls_pqc_real_encrypted.pcap (NEW!)"
echo "   → Proves encryption is real"
echo "   → Shows ML-KEM-512 + Dilithium markers"
echo "   → Demonstrates quantum-resistant security"
echo ""
echo "Key Points:"
echo "  ✓ Post-Quantum algorithms integrated"
echo "  ✓ DTLS 1.3 protocol compliance"
echo "  ✓ Real encryption demonstrated"
echo "  ✓ Wireshark-compatible captures"
echo "  ✓ Complete documentation provided"
echo ""

echo "============================================================"

exit 0
