#!/usr/bin/env python3
"""
Generate PQC test keys for Dilithium-based mutual authentication
Creates placeholder keys that will be embedded in the firmware
"""

import os
import struct

def create_test_key(name, key_type, size):
    """Create a test key file with predictable content"""
    print(f"Creating {name} ({size} bytes)...")
    
    # Create a deterministic test key based on the name
    seed = sum(ord(c) for c in name)
    data = bytearray()
    
    for i in range(size):
        # Simple PRNG for test data
        seed = (seed * 1103515245 + 12345) & 0xFFFFFFFF
        data.append(seed & 0xFF)
    
    return bytes(data)

def main():
    print("=" * 50)
    print("PQC Test Key Generation (Dilithium Placeholder)")
    print("=" * 50)
    print()
    
    # Create output directory
    os.makedirs("pqc_certs", exist_ok=True)
    
    # Dilithium Level 2 (ML-DSA-44) approximate sizes
    # These are placeholders - real keys would be generated by wolfSSL
    keys = [
        ("pqc_certs/ca-pub.der", "CA Public", 1312),
        ("pqc_certs/ca-key.der", "CA Private", 2560),
        ("pqc_certs/server-pub.der", "Server Public", 1312),
        ("pqc_certs/server-key.der", "Server Private", 2560),
        ("pqc_certs/client-pub.der", "Client Public", 1312),
        ("pqc_certs/client-key.der", "Client Private", 2560),
    ]
    
    for filepath, name, size in keys:
        data = create_test_key(name, "dilithium2", size)
        with open(filepath, "wb") as f:
            f.write(data)
        print(f"  ✓ {filepath} ({size} bytes)")
    
    print()
    print("=" * 50)
    print("✓ Test keys generated!")
    print("=" * 50)
    print()
    print("NOTE: These are PLACEHOLDER keys for development.")
    print("For production, compile and run tools/generate_pqc_keys.c")
    print("with a properly built wolfSSL library.")
    print()
    print("Next: Run ./tools/embed_certs.sh to create C headers")

if __name__ == "__main__":
    main()
